from __future__ import annotations

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def build_grc_summary_pdf(
    *,
    organization_name: str,
    industry: str,
    frameworks: list[str],
    documents: list[dict],
) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=LETTER, title="Midnight GRC Summary")
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Midnight GRC Summary", styles["Title"]))
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"Organization: {organization_name}", styles["BodyText"]))
    story.append(Paragraph(f"Industry: {industry}", styles["BodyText"]))
    story.append(Paragraph(f"Framework Scope: {', '.join(frameworks) or 'Not specified'}", styles["BodyText"]))
    story.append(Spacer(1, 16))

    story.append(Paragraph("Program Snapshot", styles["Heading2"]))
    story.append(Paragraph(
        "This summary reflects artifacts generated by Midnight for preparation and alignment work. "
        "It is intended to support readiness efforts and does not claim certification or compliance status.",
        styles["BodyText"],
    ))
    story.append(Spacer(1, 12))

    table_rows = [["Artifact", "Type", "Status", "Timestamp"]]
    for item in documents:
        table_rows.append([
            item.get("name", "Untitled"),
            item.get("doc_type", ""),
            item.get("status", ""),
            item.get("timestamp", ""),
        ])

    if len(table_rows) == 1:
        table_rows.append(["No generated artifacts yet", "-", "empty", "-"])

    table = Table(table_rows, colWidths=[220, 70, 80, 140])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#10131a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cfd6e4")),
        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
    ]))
    story.append(table)
    story.append(Spacer(1, 16))

    story.append(Paragraph("Framework Positioning", styles["Heading2"]))
    for framework in frameworks:
        story.append(Paragraph(
            f"{framework}: Midnight maps generated artifacts against bounded framework guidance for preparation and review.",
            styles["BodyText"],
        ))
        story.append(Spacer(1, 6))

    doc.build(story)
    return buffer.getvalue()
